name: bvhar-dev
channels:
  - conda-forge
dependencies:
  - python>=3.10
  - libboost-devel>=1.88.0
  - eigen>=3.4.0
  - spdlog
  - pybind11>=2.11.0
  - scikit-build-core>=0.8.0
  - lbfgspp
  - numpy
  - pandas
  - pip
  - pytest
  - pytest-cov
  - jupyter
  - pip:
      - quartodoc
      - griffe
