name: bvhar-env
channels:
  - conda-forge
dependencies:
  - python>=3.10
  - libboost-headers>=1.84.0
  - eigen>=3.4.0
  - spdlog
  - pybind11>=2.11.0
  - scikit-build-core>=0.8.0
  - lbfgspp
  - numpy
  - pandas
  - pip
  - pytest
  - pip:
      - quartodoc
