name: bvhar-env
channels:
  - conda-forge
dependencies:
  - python>=3.10
  - boost-cpp>=1.84.0
  - eigen>=3.4.0
  - spdlog
  - pybind11
  - numpy
  - pandas
  - pip
  - pytest
  - pip:
      - quartodoc
