var searchData=
[
  ['varforecaster_0',['varforecaster',['../classbaecon_1_1bvhar_1_1VarForecaster.html#a8959044d509a3f6aa42bee6c5523c513',1,'baecon::bvhar::VarForecaster::VarForecaster(const OlsFit &amp;fit, int step, const Eigen::MatrixXd &amp;response_mat, bool include_mean, BVHAR_OPTIONAL&lt; std::unique_ptr&lt; OlsErrorGenerator &gt; &gt; dgp_updater=boost::none)'],['../classbaecon_1_1bvhar_1_1VarForecaster.html#a75bd87cf9e5096e5a93b28d3854c71b9',1,'baecon::bvhar::VarForecaster::VarForecaster(const OlsFit &amp;fit, std::unique_ptr&lt; OlsExogenForecaster &gt; exogen_updater, int step, const Eigen::MatrixXd &amp;response_mat, bool include_mean, BVHAR_OPTIONAL&lt; std::unique_ptr&lt; OlsErrorGenerator &gt; &gt; dgp_updater=boost::none)']]],
  ['varoutforecastrun_1',['VarOutforecastRun',['../classbaecon_1_1bvhar_1_1VarOutforecastRun.html#aac8c1fd58dfa107be7d3c10bdba78303',1,'baecon::bvhar::VarOutforecastRun']]],
  ['varsv_5fh0_2',['varsv_h0',['../namespacebaecon_1_1bvhar.html#abf891dc3456cf4d9c4c220e391caa1dd',1,'baecon::bvhar']]],
  ['varsv_5fht_3',['varsv_ht',['../namespacebaecon_1_1bvhar.html#a68b3a59e4870c0048cb2fac1a1acc3a6',1,'baecon::bvhar']]],
  ['varsv_5fsigh_4',['varsv_sigh',['../namespacebaecon_1_1bvhar.html#aed1eabc81c66ec5786de0dd5105a697d',1,'baecon::bvhar']]],
  ['vharforecaster_5',['vharforecaster',['../classbaecon_1_1bvhar_1_1VharForecaster.html#ab3fde74049fe89109df0ee7a86e12933',1,'baecon::bvhar::VharForecaster::VharForecaster(const OlsFit &amp;fit, int step, const Eigen::MatrixXd &amp;response_mat, const Eigen::MatrixXd &amp;har_trans, bool include_mean, BVHAR_OPTIONAL&lt; std::unique_ptr&lt; OlsErrorGenerator &gt; &gt; dgp_updater=boost::none)'],['../classbaecon_1_1bvhar_1_1VharForecaster.html#a9c8f4887b1708e2d03e88a1f3497f939',1,'baecon::bvhar::VharForecaster::VharForecaster(const OlsFit &amp;fit, std::unique_ptr&lt; OlsExogenForecaster &gt; exogen_updater, int step, const Eigen::MatrixXd &amp;response_mat, const Eigen::MatrixXd &amp;har_trans, bool include_mean, BVHAR_OPTIONAL&lt; std::unique_ptr&lt; OlsErrorGenerator &gt; &gt; dgp_updater=boost::none)']]],
  ['vharoutforecastrun_6',['VharOutforecastRun',['../classbaecon_1_1bvhar_1_1VharOutforecastRun.html#a19512347adfe941143eebe3fbbbf5ef2',1,'baecon::bvhar::VharOutforecastRun']]]
];
