[project]
name = "bvhar"
dynamic = ["version"]
description = "Bayesian multivariate time series modeling"
readme = "README.md"
authors = [
    { name = "Young Geun Kim", email = "ygeunkimstat@gmail.com" }
]
keywords = [
    "bayesian",
    "time series"
]
dependencies = [
    "numpy",
    "pandas"
]
classifiers=[
  "Development Status :: 2 - Pre-Alpha",
  "Intended Audience :: Science/Research",
  "License :: OSI Approved :: MIT License",
  "Programming Language :: C++",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: Implementation :: CPython",
  "Topic :: Scientific/Engineering :: Mathematics"
]
requires-python = ">=3.10"
license = {file = "LICENSE"}

[project.urls]
"Homepage" = "https://ygeunkim.github.io/package/bvhar/python/"
"Bug Reports" = "https://github.com/ygeunkim/bvhar/issues"
"Source" = "https://github.com/ygeunkim/bvhar/tree/develop/python"

[project.optional-dependencies]
doc = [
    "ipykernel",
    "ipython<=8.12",
    "nbclient",
    "nbformat",
    "quartodoc"
]
dev = [
    "pytest",
    "jupyter",
    "quartodoc"
]

[build-system]
requires = [
    "scikit-build-core>=0.8.0",
    "pybind11>=2.11.0"
]
build-backend = "scikit_build_core.build"

[tool.scikit-build]
cmake.minimum-version = "3.10"
cmake.build-type = "Release"
wheel.install-dir = "bvhar"

[tool.scikit-build.metadata.version]
provider = "scikit_build_core.metadata.regex"
input = "../DESCRIPTION"
regex = "^Version:\\s*(?P<value>.+)$"

[tool.pytest.ini_options]
testpaths = ["tests"]