#' Forecasting Lines and Region
#' 
#' This function draws h-step ahead forecasts their confidence (credible) region.
#' 
#' @param mapping Set of aesthetic mappings created by \code{\link[ggplot2:aes]{ggplot2::aes}} or \code{\link[ggplot2:aes_]{ggplot2::aes_}}.
#' If specified and \code{inherit.aes = TRUE} (the default), it is combined with the default mapping at the top level of the plot.
#' You must supply mapping if there is no plot mapping.
#' @param data The data to be displayed in this layer.
#' This should be generated by interal function, \code{gather_predbvhar}.
#' @param stat The statistical transformation to use on the data for this layer, as a string.
#' @param position Position adjustment, either as a string, or the result of a call to a position adjustment function.
#' @param ci_param Parameter lists for \code{\link[ggplot2:geom_ribbon]{ggplot2::geom_ribbon}}
#' @param line_param Parameter lists for \code{\link[ggplot2:geom_path]{ggplot2::geom_path}}
#' @param label_param Parameter lists for \code{\link[ggrepel:geom_label_repel]{ggrepel::geom_label_repel}}
#' @param inherit.aes If \code{FALSE}, overrides the default aesthetics, rather than combining with them.
#' This is most useful for helper functions that define both data and aesthetics and shouldn't inherit behaviour from the default plot specification,
#' e.g. \code{\link[ggplot2:borders]{ggplot2::borders}}.
#' @details 
#' \code{gather_predbvhar} produces a \code{tibble} with columns named
#' 
#' \itemize{
#'   \item forecast - If the row is observed one or forecasted one
#'   \item id - Index of the row
#'   \item variable - Name of the variable
#'   \item value_forecast - Point forecasts
#'   \item value_lower_joint - Lower CI
#'   \item value_upper_joint - Upper CI
#'   \item model - Fitting Model
#'   \item x_label - Column to be used labeling, x-axis: Every row but one is \code{NA}
#'   \item y_label - Column to be used labeling, y-axis: Every row but one is \code{NA}
#' }
#' 
#' @importFrom ggplot2 aes layer
#' @importFrom ggrepel GeomLabelRepel
#' @export
geom_predbvhar <- function(mapping = NULL, 
                           data = NULL, 
                           stat = "identity", 
                           position = "identity", 
                           ci_param = list(fill = "grey70", alpha = .7, colour = NA, ...),
                           line_param = list(...),
                           label_param = list(na.rm = TRUE, nudge_x = 0, nudge_y = 0, label.size = .25, alpha = .7, ...),
                           inherit.aes = TRUE) {
  ci_layer <- layer(
    geom = "ribbon",
    stat = "identity",
    data = data,
    mapping = aes(ymin = value_lower_joint, ymax = value_upper_joint),
    position = position,
    params = ci_param,
    inherit.aes = inherit.aes
  )
  line_layer <- layer(
    geom = "path",
    stat = "identity",
    data = data,
    mapping = aes(linetype = forecast),
    position = position,
    params = line_param,
    inherit.aes = inherit.aes,
    show.legend = FALSE
  )
  label_layer <- layer(
    geom = GeomLabelRepel,
    stat = "identity",
    data = data,
    mapping = aes(x = x_label, y = y_label, label = model),
    position = position,
    params = label_param,
    inherit.aes = inherit.aes,
    show.legend = FALSE
  )
  list(ci_layer, line_layer, label_layer)
}
