# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Build Y0 matrix in VAR(p)
#' 
#' @param x Matrix, time series data
#' @param p VAR lag
#' @param t starting index to extract
#' 
#' @details
#' Given data Y,
#' \deqn{Y0 = [y_t^T, y_{t + 1}^T, \ldots, y_{t + n - p - 1}^T]^T}
#' is the (n - p) x m matrix.
#' 
#' In case of Y0, t = p + 1.
#' This function is used when constructing X0.
#' 
#' @useDynLib bvhar
#' @importFrom Rcpp sourceCpp
#' @export
build_y0 <- function(x, p, t) {
    .Call('_bvhar_build_y0', PACKAGE = 'bvhar', x, p, t)
}

#' Build X0 matrix in VAR(p)
#' 
#' @param x Matrix, time series data
#' @param p VAR lag
#' 
#' @details
#' X0 is
#' \deqn{X0 = [Y_p, \ldots, Y_1, 1]}
#' i.e. (n - p) x (mp + 1) matrix
#' 
#' @useDynLib bvhar
#' @importFrom Rcpp sourceCpp
#' @export
build_design <- function(x, p) {
    .Call('_bvhar_build_design', PACKAGE = 'bvhar', x, p)
}

#' Compute VAR(p) Coefficient Matrices and Fitted Values
#' 
#' @param x X0 processed by \code{\link{build_design}}
#' @param y Y0 processed by \code{\link{build_y0}}
#' @details
#' Given Y0 and Y0, the function estimate least squares
#' Y0 = X0 B + Z
#' 
#' @useDynLib bvhar
#' @importFrom Rcpp sourceCpp
#' @export
estimate_var <- function(x, y) {
    .Call('_bvhar_estimate_var', PACKAGE = 'bvhar', x, y)
}

#' Build a Linear Transformation Matrix for Vector HAR
#' 
#' @param m integer, dimension
#' @details
#' VHAR is linearly restricted VAR(22) in Y0 = X0 B + Z.
#' 
#' @useDynLib bvhar
#' @importFrom Rcpp sourceCpp
#' @export
scale_har <- function(m) {
    .Call('_bvhar_scale_har', PACKAGE = 'bvhar', m)
}

#' Compute Vector HAR Coefficient Matrices and Fitted Values
#' 
#' @param x X0 processed by \code{\link{build_design}}
#' @param y Y0 processed by \code{\link{build_y0}}
#' @details
#' Given Y0 and Y0, the function estimate least squares
#' Y0 = X1 Phi + Z
#' 
#' @useDynLib bvhar
#' @importFrom Rcpp sourceCpp
#' @export
estimate_har <- function(x, y) {
    .Call('_bvhar_estimate_har', PACKAGE = 'bvhar', x, y)
}

#' @useDynLib bvhar
#' @importFrom Rcpp sourceCpp
#' @export
compute_var <- function(z, s, k) {
    .Call('_bvhar_compute_var', PACKAGE = 'bvhar', z, s, k)
}

#' @useDynLib bvhar
#' @importFrom Rcpp sourceCpp
#' @export
kroneckerprod <- function(x, y) {
    .Call('_bvhar_kroneckerprod', PACKAGE = 'bvhar', x, y)
}

