#' Forecast Region for VAR(p)
#' 
#' Compute forecast region VAR(p) model
#' @param object predvarlse object
#' @param level Confidence level
#' @param ... not used
#' 
#' @details 
#' For h-step forecasting (e.g. n + 1, ... n + h),
#' joint forecast region of \eqn{100(1-\alpha)}\% can be computed by
#' \deqn{\left\{ (y_{k, 1}, y_{k, h}) \mid y_{k, n}(i) - z_{(\alpha / 2h)} \sigma_n(i) \le y_{n, i} \le y_{k, n}(i) + z_{(\alpha / 2h)} \sigma_k(i), i = 1, \ldots, h \right\}}
#' See the pp41 of Lütkepohl (2007).
#' 
#' To compute covariance matrix, it needs VMA representation:
#' \deqn{Y_{t}(h) = c + \sum_{i = h}^{\infty} W_{i} \epsilon_{t + h - i} = c + \sum_{i = 0}^{\infty} W_{h + i} \epsilon_{t - i}}
#' 
#' Then
#' 
#' \deqn{\Sigma_y(h) = MSE \left[ y_t(h) \right] = \sum_{i = 0}^{h - 1} W_i \Sigma_{\epsilon} W_i^T = \Sigma_y(h - 1) + W_{h - 1} \Sigma_{\epsilon} W_{h - 1}^T}
#' 
#' @references 
#' Lütkepohl, H. (2007). \emph{New Introduction to Multiple Time Series Analysis}. Springer Publishing. \url{https://doi.org/10.1007/978-3-540-27752-1}
#' @order 2
#' @export
forecast_region <- function(object, h, level = .05, ...) {
  h <- nrow(object) # h-step
  z <- qnorm(level / (2 * h), lower.tail = FALSE) # + z(alpha / 2h)
  # fill the rest
  z
}

#' Plot Forecast Result
#' 
#' Plots the forecasting result
#' 
#' @param object \code{predbvhar} object usually generated by \code{predict()} function in this package
#' @param type Divide variables using \code{\link[ggplot2]{facet_grid}} ("facet": default) or just line type ("color")
#' @param ... additional option for \code{\link[ggplot2]{geom_path}}
#' 
#' @importFrom ggplot2 ggplot aes geom_path facet_grid labs element_blank
#' @importFrom dplyr bind_rows mutate n
#' @importFrom tidyr pivot_longer
#' @export
autoplot.predbvhar <- function(object, type = c("facet", "shape"), ...) {
  type <- match.arg(type)
  Y <- 
    object$y %>% 
    as.data.frame() %>% 
    mutate(forecast = FALSE)
  PRED <- 
    object$forecast %>% 
    as.data.frame() %>% 
    mutate(forecast = TRUE)
  p <- 
    Y %>% 
    bind_rows(PRED) %>% 
    mutate(id = 1:n()) %>% 
    pivot_longer(-c(id, forecast), names_to = "variable", values_to = "value") %>% 
    ggplot(aes(x = id, y = value))
  switch(
    type,
    "facet" = {
      p +
        geom_path(aes(color = forecast), ...) +
        facet_grid(variable ~ ., scales = "free_y") +
        labs(
          x = element_blank(),
          y = element_blank()
        )
    },
    "shape" = {
      p +
        geom_path(aes(linetype = variable, color = forecast), ...) +
        labs(
          x = element_blank(),
          y = element_blank()
        )
    }
  )
}
