#' Plot Forecast Result
#' 
#' Plots the forecasting result with forecast regions.
#' 
#' @param object \code{predbvhar} object usually generated by \code{predict()} function in this package
#' @param type Divide variables using \code{\link[ggplot2]{facet_grid}} ("grid": default) or \code{\link[ggplot2]{facet_wrap}} ("wrap")
#' @param ci_fill color of CI
#' @param x_cut plot x axes from \code{x_cut} for visibility
#' @param NROW \code{nrow} of \code{\link[ggplot2]{facet_wrap}}
#' @param NCOL \code{ncol} of \code{\link[ggplot2]{facet_wrap}}
#' @param ... additional option for \code{\link[ggplot2]{geom_path}}
#' 
#' @importFrom ggplot2 ggplot aes geom_path geom_ribbon facet_grid labs element_blank
#' @importFrom dplyr bind_rows mutate n left_join filter
#' @importFrom purrr reduce
#' @importFrom tidyr pivot_longer
#' @export
autoplot.predbvhar <- function(object, type = c("grid", "wrap"), ci_fill = "grey70", x_cut = 1, NROW = NULL, NCOL = NULL, ...) {
  type <- match.arg(type)
  Y <- 
    object$y %>% 
    as.data.frame() %>% 
    mutate(forecast = FALSE)
  PRED <- 
    object$forecast %>% 
    as.data.frame() %>% 
    mutate(forecast = TRUE)
  forecast_list <- 
    lapply(
      c("forecast", "lower_joint", "upper_joint"),
      function(comp) {
        PRED <- 
          object[[comp]] %>% 
          as.data.frame() %>% 
          mutate(forecast = TRUE)
        Y %>% 
          bind_rows(PRED) %>% 
          mutate(id = 1:n()) %>% 
          pivot_longer(-c(id, forecast), names_to = "variable", values_to = paste("value", comp, sep = "_"))
      }
    ) %>% 
    reduce(left_join, by = c("id", "variable", "forecast"))
  p <- 
    forecast_list %>% 
    filter(id >= x_cut) %>% 
    ggplot(aes(x = id, y = value_forecast))
  switch(
    type,
    "grid" = {
      p +
        geom_ribbon(aes(ymin = value_lower_joint, ymax = value_upper_joint), fill = ci_fill) +
        geom_path(aes(color = forecast), show.legend = FALSE, ...) +
        facet_grid(variable ~ ., scales = "free_y") +
        labs(
          x = element_blank(),
          y = element_blank()
        )
    },
    "wrap" = {
      p +
        geom_ribbon(aes(ymin = value_lower_joint, ymax = value_upper_joint), fill = ci_fill) +
        geom_path(aes(color = forecast), show.legend = FALSE, ...) +
        facet_wrap(variable ~ ., nrow = NROW, ncol = NCOL, scales = "free_y") +
        labs(
          x = element_blank(),
          y = element_blank()
        )
    }
  )
}

#' Evaluate the Model Based on MSPE (Mean Squared Prediction Error)
#' @param x \code{predbvhar} object
#' @param y test data to be compared
#' @param ... not used
#' 
#' @export
mse <- function(x, y, ...) {
  UseMethod("mse", x)
}

#' Compute MSE
#' 
#' @param x \code{predbvhar} object
#' @param y test data to be compared. should be the same format with the train data and predict$forecast.
#' @param ... not used
#' 
#' @export
mse.predbvhar <- function(x, y, ...) {
  apply(y - x$forecast, 2, function(x) mean(x^2))
}

#' Evaluate the Model Based on MAPE (Mean Absolute Percentage Error)
#' @param x \code{predbvhar} object
#' @param y test data to be compared
#' @param ... not used
#' 
#' @export
mape <- function(x, y, ...) {
  UseMethod("mape", x)
}

#' Compute MAPE
#' 
#' @param x \code{predbvhar} object
#' @param y test data to be compared. should be the same format with the train data and predict$forecast.
#' @param ... not used
#' 
#' @export
mape.predbvhar <- function(x, y, ...) {
  apply((y - x$forecast) / y, 2, function(x) mean(abs(x)))
}
