#' Plot Forecast Result
#' 
#' Plots the forecasting result with forecast regions.
#' 
#' @param object \code{predbvhar} object usually generated by \code{predict()} function in this package
#' @param type Divide variables using \code{\link[ggplot2]{facet_grid}} ("facet": default) or just line type ("color")
#' @param ... additional option for \code{\link[ggplot2]{geom_path}}
#' @details 
#' For h-step forecasting (e.g. n + 1, ... n + h),
#' joint forecast region of \eqn{100(1-\alpha)}\% can be computed by
#' \deqn{\left\{ (y_{k, 1}, y_{k, h}) \mid y_{k, n}(i) - z_{(\alpha / 2h)} \sigma_n(i) \le y_{n, i} \le y_{k, n}(i) + z_{(\alpha / 2h)} \sigma_k(i), i = 1, \ldots, h \right\}}
#' See the pp41 of Lütkepohl (2007).
#' 
#' @importFrom ggplot2 ggplot aes geom_path geom_ribbon facet_grid labs element_blank
#' @importFrom dplyr bind_rows mutate n
#' @importFrom tidyr pivot_longer
#' @export
autoplot.predbvhar <- function(object, type = c("facet", "shape"), ...) {
  type <- match.arg(type)
  Y <- 
    object$y %>% 
    as.data.frame() %>% 
    mutate(forecast = FALSE)
  PRED <- 
    object$forecast %>% 
    as.data.frame() %>% 
    mutate(forecast = TRUE)
  p <- 
    Y %>% 
    bind_rows(PRED) %>% 
    mutate(id = 1:n()) %>% 
    pivot_longer(-c(id, forecast), names_to = "variable", values_to = "value") %>% 
    ggplot(aes(x = id, y = value))
  # find the first id starting with forecast == TRUE
  # make df of joint CI with that id
  # geom_ribbon
  switch(
    type,
    "facet" = {
      p +
        geom_path(aes(color = forecast), ...) +
        facet_grid(variable ~ ., scales = "free_y") +
        labs(
          x = element_blank(),
          y = element_blank()
        )
    },
    "shape" = {
      p +
        geom_path(aes(linetype = variable, color = forecast), ...) +
        labs(
          x = element_blank(),
          y = element_blank()
        )
    }
  )
}
