on:
  push:
    branches: [main, master, 'hotfix/*', 'release/*', develop]
  pull_request:
    branches: [main, master, 'hotfix/*', 'release/*', develop]

name: py-github-check

jobs:
  build:
    runs-on: ${{ matrix.os }}

    if: ${{ !contains(github.event.head_commit.message, '[skip py]') }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.10', '3.11', '3.12', '3.13', '3.14']
    
    name: ${{ matrix.os }} (${{ matrix.python-version }})

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Verify git
        run: git --version

      - name: Verify C++ libraries on non-Windows
        if: runner.os != 'Windows'
        run: mkdir temp-dir
      
      - name: Verify C++ libraries on Windows
        if: runner.os == 'Windows'
        run: New-Item -ItemType Directory -Force -Path temp-dir

      - name: Install package from github
        run: |
          pip install --upgrade pip
          python -m pip install -e 'git+https://github.com/ygeunkim/bvhar.git#egg=bvhar&subdirectory=python'
        working-directory: temp-dir

      - name: Install dev version from github
        run: |
          pip install --upgrade pip
          python -m pip install -e 'git+https://github.com/ygeunkim/bvhar.git@develop#egg=bvhar&subdirectory=python'
        working-directory: temp-dir
      
      - name: Verify installation
        run: pip list
        working-directory: temp-dir
      
      - name: OpenMP check
        run: python -c "from bvhar.utils import checkomp; checkomp.check_omp()"
        working-directory: temp-dir
